#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import subprocess
from pathlib import Path

# Can be run manually from here or from root dir

root_path = Path.cwd()

if not (root_path / 'docs').exists():
    root_path = root_path.parent

docs_path = root_path / 'docs'
docs_source_path = root_path / 'docs' / 'source'

for p in Path(docs_source_path).iterdir():
    if p.name not in ['img', 'conf.py', 'index.rst', '_static', '_templates']:
        p.unlink()

# subprocess.run(['make', 'html'], shell=True, cwd=docs_path, check=True)
subprocess.run(['sphinx-apidoc', '-f', '-e', '-o', 'source', '../predictit'], shell=True, cwd=docs_path, check=True)

subprocess.run(['git', 'add', 'docs'], shell=True, cwd=root_path, check=True)
